# Generated by Django 5.2.7 on 2025-10-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_buses', models.IntegerField(default=0)),
                ('active_buses', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('active_routes', models.IntegerField(default=0)),
                ('students_transported_today', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Statistics',
            },
        ),
    ]
