# Generated by Django 5.2.7 on 2025-10-08 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_notifications', '0001_initial'),
        ('buses', '0002_alter_bus_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buses.bus'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('delay', 'Bus Delay'), ('arrival', 'Bus Arrival'), ('emergency', 'Emergency'), ('route_change', 'Route Change'), ('maintenance', 'Maintenance'), ('weather', 'Weather Alert'), ('info', 'Information')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('delay', 'Bus Delay'), ('arrival', 'Bus Arrival'), ('emergency', 'Emergency'), ('route_change', 'Route Change'), ('maintenance', 'Maintenance'), ('weather', 'Weather Alert'), ('info', 'Information')], max_length=20),
        ),
    ]
